---
- name: Collection instance info
  os_server_info:
    cloud: "{{ cloud }}"
  register: openstack_instances

- name: Build In-Memory inventory
  add_host:
    host: "{{ instance.name }}.{{ internal_domain }}"
    groups: 
      - "{{ instance.metadata.server_roll }}"
      - "{{ instance.metadata.AnsibleGroup }}"
    ansible_host: "{{ instance.private_v4 }}"
    ssh_private_key_file: "{{ HOME }}/.ssh/{{ GUID }}key.pem"
  when: instance.metadata.AnsibleGroup == "osp_instances"
  loop: "{{ openstack_instances.openstack_servers }}"
  loop_control:
    loop_var: instance
